# Default values for hcbm-workflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/hzero-hzero/hcbm-workflow
  pullPolicy: Always

preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  timeout: 120
  preInitDB:
    enable: false
    datasource:
      url: jdbc:mysql://db.hzero.org:3306/hzero_workflow?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: hcbm
      password: hcbm

deployment:
  managementPort: 8161

env:
  open:
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    SPRING_DATASOURCE_URL: jdbc:mysql://db.hzero.org:3306/hzero_workflow?useUnicode=true&characterEncoding=utf-8&useSSL=false
    SPRING_DATASOURCE_USERNAME: hcbm
    SPRING_DATASOURCE_PASSWORD: hcbm
    SPRING_REDIS_HOST: redis.hzero.org
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 40000
    RIBBON_READ_TIMEOUT: 30000
    RIBBON_CONNECT_TIMEOUT: 3000
    HZERO_WORKFLOW_MAIL_HOST: stmp.163.com
    HZERO_WORKFLOW_MAIL_PORT: 25
    HZERO_WORKFLOW_MAIL_USERNAME: hzero@163.com
    HZERO_WORKFLOW_MAIL_PASSWORD: hzero
    DATABASE_TYPE: mysql
    JAVA_OPTS: >
      -Xms1024m
      -Xmx1536m
metrics:
  path: /prometheus
  group: spring-boot

logs:
  parser: spring-boot

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # subPath:

service:
  enabled: false
  type: ClusterIP
  port: 8160
  
ingress:
  enabled: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.7Gi
  requests:
    # cpu: 100m
    memory: 1.2Gi
hzero:
  HZERO_NODE_GROUP_ID: 0
  HZERO_PRODUCT_CODE: DEFAULT
  HZERO_PRODUCT_VERSION_CODE: DEFAULT
  HZERO_PRODUCT_ENV_CODE: DEFAULT
  HZERO_SERVICE_VERSION_CODE: DEFAULT