# Default values for hcbm-message.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/hzero-hzero/hcbm-message
  pullPolicy: Always

preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  timeout: 120
  preInitDB:
    enable: false
    datasource:
      url: jdbc:mysql://db.hzero.org:3306/hzero_message?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: hcbm
      password: hcbm

deployment:
  managementPort: 8121

env:
  open:
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    SPRING_CLOUD_CONFIG_ENABLED: false
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    SECURITY_OAUTH2_USER_INFO_URI: http://hzero-oauth/oauth/api/user
    SPRING_DATASOURCE_URL: jdbc:mysql://db.hzero.org:3306/hzero_message?useUnicode=true&characterEncoding=utf-8&useSSL=false
    SPRING_DATASOURCE_USERNAME: hcbm
    SPRING_DATASOURCE_PASSWORD: hcbm
    SPRING_REDIS_HOST: redis.hzero.org
    SPRING_REDIS_DATABASE: 1
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 40000
    RIBBON_READ_TIMEOUT: 30000
    RIBBON_CONNECT_TIMEOUT: 3000
    LOGGING_LEVEL: info
    HZERO_DB_OWNER:
    JAVA_OPTS: >
      -Xms1024m
      -Xmx1536m
metrics:
  path: /prometheus
  group: spring-boot

logs:
  parser: spring-boot

persistence:
  enabled: false

service:
  enabled: false
  type: ClusterIP
  port: 8120
  name: hzero-message

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.7Gi
  requests:
    # cpu: 100m
    memory: 1.2Gi
hzero:
  HZERO_NODE_GROUP_ID: 0
  HZERO_PRODUCT_CODE: DEFAULT
  HZERO_PRODUCT_VERSION_CODE: DEFAULT
  HZERO_PRODUCT_ENV_CODE: DEFAULT
  HZERO_SERVICE_VERSION_CODE: DEFAULT