spring:
  application:
    name: hzero-interface
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306/hzero_interface?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:hcbm}
    password: ${SPRING_DATASOURCE_PASSWORD:hcbm}
  redis:
    host: redis.hzero.org
    port: 6379
    database: 1
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://dev.hzero.org:8000/eureka}

hzero:
  interface:
    init-cache: ${HZERO_INTERFACE_INIT_CACHE:true}
    thread-pool-properties:
      core-pool-size: 1
      keep-alive-seconds: 600
      allow-core-thread-time-out: true
      thread-name-prefix: HDTT-ASYNC-TASK-EXECUTOR
  data:
    permission:
      db-owner: ${HZERO_DB_OWNER:}

logging:
  level:
    org.apache.ibatis: ${LOGGING_LEVEL:debug}
    io.choerodon: ${LOGGING_LEVEL:debug}
    org.hzero: ${LOGGING_LEVEL:debug}