# Default values for hcbm-workflow-editor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/hzero-hzero/hcbm-workflow-editor
  pullPolicy: Always


deployment:
  managementPort: 8171

env:
  open:
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    SPRING_CLOUD_CONFIG_ENABLED: false
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    SPRING_REDIS_HOST: redis.hzero.org
    HZERO_WORKFLOW_SERVICE_URL: http://dev.hzero.org:8080/hwfl
    ## config-server
    JAVA_OPTS: >
      -Xms1024m
      -Xmx1536m
metrics:
  path: /prometheus
  group: spring-boot

logs:
  parser: spring-boot

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # subPath:

service:
  enabled: false
  type: ClusterIP
  port: 8170

ingress:
  enabled: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.7Gi
  requests:
    # cpu: 100m
    memory: 1.2Gi
hzero:
  HZERO_NODE_GROUP_ID: 0
  HZERO_PRODUCT_CODE: DEFAULT
  HZERO_PRODUCT_VERSION_CODE: DEFAULT
  HZERO_PRODUCT_ENV_CODE: DEFAULT
  HZERO_SERVICE_VERSION_CODE: DEFAULT